# =====================================================
# 실행할 프로파일 선택: rag 또는 tool
#   - 기본값: rag
#   - 실행 시 덮어쓰기: --spring.profiles.active=tool
# =====================================================
spring:
  profiles:
    active: tool

---
# =====================================================
# [RAG] 프로파일
# =====================================================
spring:
  config:
    activate:
      on-profile: rag
  application:
    name: chat
    cli: false
  elasticsearch:
    uris: http://localhost:9200 # 로컬 도커로 띄운 상용 엘라스틱서치 서버 주소
  ai:
    openai:
      # 환경변수 값
      api-key: ${OPENAI_API_KEY}
      chat:
        # 실제 사용할 대화형 AI의 모델명
        model: openai/gpt-4.1-nano
        # GitHub Models 서버로 요청을 보냄
        base-url: https://models.github.ai/inference
        # 세부 API 경로
        completions-path: /chat/completions
    #[2] Ollama 설정
    ollama:
      init:
        pull-model-strategy: when_missing
      chat:
        # hugging face의 모델명 입력
        model: hf.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF
      embedding:
        options:
          model: bge-m3
    # (C) 상용 백터 데이터베이스(Elasticsearch) 연동
    vectorstore:
      elasticsearch:
        initialize-schema: true # 서버 구동 시 해당 인덱스가 없으면 자동으로 생성
        index-name: spring-ai-document-index # 벡터 데이터가 저장될 엘라스틱서치 인덱스 이름
        dimensions: 1024               # bge-m3 모델의 고유 출력 벡터 차원 수 지정 (필수)
        similarity: cosine             # 벡터 간의 거리(유사도)를 계산할 수학 공식 (코사인 유사도)

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

app:
  rag:
    documents-location-pattern: classpath:spring-ai-llm2.pdf
  etl:
    pipeline:
      init: true
  vectorstore:
    in-memory:
      enabled: false
  cli:
    enabled: true

---
# =====================================================
# [TOOL] 프로파일 (추후 설정 추가 예정)
# =====================================================
spring:
  config:
    activate:
      on-profile: tool
  application:
    name: tool  # 애플리케이션 이름
  ai:
    model:
      chat: openai  # 여러 Chat 모델 사용 시 auto-configurations 에서 사용할 모델 설정 필요 예: openai, ollama
    openai:
      api-key: ${OPENAI_API_KEY}  # OpenAI 호출 API를 제공하는 Provider의 경우 아래 내용을 적절히 수정
      chat:
        model: openai/gpt-4.1-nano
        base-url: https://models.github.ai/inference  # 설정하지 않으면 기본 OpenAI api 호출 주소를 사용
        completions-path: /chat/completions  # OpenAI 기본값은 /v1/chat/completions, github 모델 사용 시 아래와 같이 수정

# 애플리케이션 커스텀 옵션 추가
app:
  cli:
    enabled: true  # CLI 모드 활성화 여부
  chat:
    default-system-prompt: 한국어를 사용하는 tool 지원 AI 입니다.  # 기본 system prompt

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG  # SimpleLoggerAdvisor 등의 Advisor에서 DEBUG 로그 출력
          tool: DEBUG  # Tool 사용 관련 DEBUG 로그 출력