spring:
  application:
    name: chat
    cli: false
  ai:
    openai:
      # 환경변수 값
      api-key: ${OPENAI_API_KEY}
      chat:
        # 실제 사용할 대화형 AI의 모델명
        model: openai/gpt-4.1-nano
        # GitHub Models 서버로 요청을 보냄
        base-url: https://models.github.ai/inference
        # 세부 API 경로
        completions-path: /chat/completions
    #[2] Ollama 설정
    ollama:
      init:
        pull-model-strategy: when_missing
      chat:
        # hugging face의 모델명 입력
        model: hf.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF
      embedding:
        options:
          model: bge-m3

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

app:
  rag:
    documents-location-pattern: classpath:spring-ai-llm.pdf
  etl:
    pipeline:
      init: true
  vectorstore:
    in-memory:
      enabled: true
  cli:
    enabled: true
